// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzyhtmlzrbxsapnsmhzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16eWh0bWx6cmJ4c2FwbnNtaHpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MzkzMTIsImV4cCI6MjA1ODMxNTMxMn0.lrKrFzJBhLdjVjm7sXQAkH-q6CytiTaDbeDMv7nXnJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);